Follow-up of #13 on failure at init
kuka-isir/ati_sensor pull request #16
Opened 2017-10-25 10:29 UTC by guihomework

Modified failure detection to stop at first major error and improved error messages

As discussed in #13 
* failure occurs earliest possible
* no API change
* muting some info (but kept xenomai message to know it is really running in xenomai mode)

Not all failure case could be tested, don't know how to produce them. But the main fail described in #13 looks like this now 
```
process[rh/ft_sensor-1]: started with pid [350]
[ INFO] [1508921479.215189932]: ATISensor IP : 192.168.10.100
[ INFO] [1508921479.215274299]: ATISensor frame : /ati_link
Could not connect to 192.168.10.100:80       => is in normal red
openSockets error: failed to connect to socket   => is bold red
Error during initialization, FT sensor NOT started   => is bold red
Sensor shutdown sucessfully
[FATAL] [1508921482.279232529]: Failed with error : FT sensor could not initialize  => is normal red coming from the node handling the init fail.
```

2017-10-25 10:53 UTC, ahoarau commented
Thanks for the PR. Could you also add the prefix [ftsensor up:port] for all messages ?

2017-10-25 11:41 UTC, ahoarau requested changes
It's missing ` #include <stdexcept>` for versions < kinetic that do not use c++11

2017-11-06 18:48 UTC, guihomework commented
@ahoarau back from holiday, finishing working on it asap

2017-11-15 19:01 UTC, guihomework commented
Fixed header and tested locally.
when working
```
[ INFO] [1510769573.025842534]: ATISensor IP : 192.168.10.100
[ INFO] [1510769573.025920675]: ATISensor frame : /ati_frame
[ft_sensor 192.168.10.101:49152] Start realtime streaming with 1 samples
[ft_sensor 192.168.10.101:49152] Using current calibration
[ft_sensor 192.168.10.101:49152] Sucessfully retrieved counts per force : 1000000
[ft_sensor 192.168.10.101:49152] Sucessfully retrieved counts per torque : 1000000
[ INFO] [1510769573.058763111]: ATISensor RDT Rate : 7000
```
when fails
```
[ INFO] [1510772385.124127616]: ATISensor IP : 192.168.10.100
[ INFO] [1510772385.124198430]: ATISensor frame : /ati_link
[ft_sensor 192.168.10.100:49152] Could not connect to 192.168.10.100
[ft_sensor 192.168.10.100:49152] openSockets error: failed to connect to socket
[ft_sensor 192.168.10.100:49152] Error during initialization, FT sensor NOT started
[ft_sensor 192.168.10.100:49152] Sensor shutdown sucessfully
[FATAL] [1510772403.495391524]: Failed with error : FT sensor could not initialize
```

2017-11-15 19:12 UTC, ahoarau commented
Good. Tiny remark :  `Sensor shutdown sucessfully` is not necessary (?)

2017-11-15 19:54 UTC, guihomework commented
I inverted the test to create a message if not shutting down properly

2017-11-15 21:20 UTC, ahoarau commented
Shall we remove this message instead ? 
If sensor is not present, then the shutdown cannot be 'not successful' :)

2017-11-16 13:21 UTC, guihomework commented
I think it is important to know when open sockets could not close correctly. The closing should handle the fact that the socket might not have been open (so should succeed to close something not open).

However I have doubts on how it was handled before my change :
https://github.com/kuka-isir/ati_sensor/blob/master/src/ft_sensor.cpp#L308
returns true if the return value is positive on both. However positive will never occur because close is never positive (https://linux.die.net/man/2/close)
So return was always false, so always 0

I suggest the following.
* handle the closing correctly. If the handle is -1 then closing is not needed BUT successful
* handle the destructor to call closing and print if something went wrong on closing. This won't print a message if everything went fine or if the sensor was not open.

2017-11-16 13:26 UTC, ahoarau commented
100% agree :+1:

2017-11-16 17:20 UTC, guihomework commented
I fixed it and there is no message shown, even if badly disconnecting and such (probably because it never fails to close the handler)

2017-11-17 14:53 UTC, ahoarau approved these changes

2017-11-17 14:56 UTC, merged